In [1]:
import torch

In [2]:
# 示例输入：Batch=2, Input length=3, Channel=4
x = torch.tensor([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

x_flatten = x.view(2, -1)
print(x_flatten)
# 输出：
# tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
#         [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])


In [4]:
# 示例输入：Batch=2, Input length=3, Channel=4
x = torch.tensor([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

x_flatten = x.view(2, 12)
print(x_flatten)
# 输出：
# tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
#         [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])


In [5]:
# 示例输入：Batch=2, Input length=3, Channel=4
x = torch.tensor([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

# 首先调整维度顺序，将input length维度放到最后
x_permuted = x.permute(0, 2, 1)  # 变成 [batch, channel, length]
x_flatten = x_permuted.reshape(2, -1)
print(x_flatten)
# 输出：
# tensor([[ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12],
#        [13, 17, 21, 14, 18, 22, 15, 19, 23, 16, 20, 24]])

tensor([[ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12],
        [13, 17, 21, 14, 18, 22, 15, 19, 23, 16, 20, 24]])


In [7]:
x = torch.tensor([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])
x = x.permute(0,2,1) # x: [Batch, Channel, Input length]
x = x.reshape(x.size(0), -1)# x: [Batch, Channel * Input length]
print(x)

tensor([[ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12],
        [13, 17, 21, 14, 18, 22, 15, 19, 23, 16, 20, 24]])


In [8]:
## 示例输入：Batch=2, Input length=3, Channel=4
import torch.nn as nn
x = torch.tensor([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])
# 使用自适应平均池化
adaptive_pool = nn.AdaptiveAvgPool2d((1))
output = adaptive_pool(x)  # 输出形状：[32, 128, 1, 1]

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [10]:
# 示例输入：Batch=2, Input length=3, Channel=4
import torch
import torch.nn as nn

x = torch.tensor([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
], dtype=torch.float32)  # 注意：需要使用float类型

# # 方法1：直接使用mean
# output = x.mean(dim=-1)  # 在最后一个维度（channel维度）上取平均
# print("输出形状:", output.shape)  # 输出形状: torch.Size([2, 3])
# print(output)


# 方法2：使用AdaptiveAvgPool1d
adaptive_pool = nn.AdaptiveAvgPool1d(1)
# 需要先调整维度顺序，将channel维度放到第二维
x_permuted = x.permute(0, 2, 1)  # [2, 4, 3]
output2 = adaptive_pool(x_permuted).squeeze(1)  # squeeze去掉长度为1的维度
print("\n使用AdaptiveAvgPool1d的输出:")
print("输出形状:", output2.shape)
print(output2)


使用AdaptiveAvgPool1d的输出:
输出形状: torch.Size([2, 4, 1])
tensor([[[ 5.],
         [ 6.],
         [ 7.],
         [ 8.]],

        [[17.],
         [18.],
         [19.],
         [20.]]])


In [13]:
avg_pool = nn.AdaptiveAvgPool2d((1, 1))

# 示例输入：Batch=2, Input length=3, Channel=4
import torch
import torch.nn as nn

x = torch.tensor([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
], dtype=torch.float32)  # 注意：需要使用float类型

x = avg_pool(x)
print(x)


tensor([[[ 6.5000]],

        [[18.5000]]])


: 